### ISSUE TITLE
pandoc from Debian jessie not supported

### ISSUE THREAD

**Issue by martinvonwittich** [Ecodev/redmine_convert_textile_to_markown#2]
Hi,

if you use the pandoc package from Debian jessie and run this script, it aborts with the following error message:

```
redmine.iserv.eu /var/www/redmine-staging # bundle exec rake convert_textile_to_markdown RAILS_ENV=production
/var/lib/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::VCF
/var/lib/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of VCF was here
Comment
WikiContent
Issuepandoc: unrecognized option `--wrap=preserve'
Try pandoc --help for more information.
rake aborted!
pandoc failed
/var/www/redmine-staging-3.3.3/lib/tasks/convert_textile_to_markdown.rake:86:in `convert_textile_to_markdown'
/var/www/redmine-staging-3.3.3/lib/tasks/convert_textile_to_markdown.rake:21:in `block (4 levels) in <top (required)>'
/var/www/redmine-staging-3.3.3/lib/tasks/convert_textile_to_markdown.rake:17:in `each'
/var/www/redmine-staging-3.3.3/lib/tasks/convert_textile_to_markdown.rake:17:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in `each'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in `block in find_each'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:50:in `find_each'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:9:in `find_each'
/var/www/redmine-staging-3.3.3/lib/tasks/convert_textile_to_markdown.rake:16:in `block (2 levels) in <top (required)>'
/var/www/redmine-staging-3.3.3/lib/tasks/convert_textile_to_markdown.rake:14:in `each'
/var/www/redmine-staging-3.3.3/lib/tasks/convert_textile_to_markdown.rake:14:in `block in <top (required)>'
/var/lib/gems/2.1.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => convert_textile_to_markdown
(See full trace by running task with --trace)
```

Apparently the pandoc from Debian jessie (1.12.4.2~dfsg-1+b14) is too old. This problem is very easy to work around - just download the most recent version from https://github.com/jgm/pandoc/releases and install it with `dpkg -i`. It doesn't have any dependencies and installs without issues. It would be nice if you could note about this in the readme.

**Comment by PowerKiKi** [comment]
This is most likely correct, but out of scope of this project. There is nothing we can do to fix it.

**Comment by martinvonwittich** [comment]
Hm, but why not add a simple note about this to the readme?

**Comment by PowerKiKi** [comment]
We [are already linking](https://github.com/Ecodev/redmine_convert_textile_to_markown#usage) to [Pandoc install documentation](http://pandoc.org/installing.html). That doc is specifically mentioning it:

> Note, however, that versions in the repositories are often old.

**Comment by graue70** [comment]
I know this is old, but a note in the docs would have helped me just now. The sentence in the [pandoc docs](https://pandoc.org/installing.html#linux) that you mention is easily overlooked.
